name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    environment:
      name: testing
    env:
      DB_HOST: ${{vars.DB_HOST}}
      DB_PORT: ${{vars.DB_PORT}}
      DB_PASSWORD: ${{vars.DB_PASSWORD}}
      DB_NAME: ${{vars.DB_NAME}}
      DB_USER: ${{vars.DB_USER}}
      SECRET_KEY: ${{vars.SECRET_KEY}}
      ALGORITHM: ${{vars.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{vars.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{vars.DB_PASSWORD}}
          POSTGRES_DB: ${{vars.DB_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
